<?php
/**
 * InlineResponseDefaultTraceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * RESTful API V1
 *
 * This is my app swagger api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nazmul.basher@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InlineResponseDefaultTraceTest Class Doc Comment
 *
 * @category    Class */
// * @description InlineResponseDefaultTrace
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponseDefaultTraceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "InlineResponseDefaultTrace"
     */
    public function testInlineResponseDefaultTrace()
    {

    }

    /**
     * Test attribute "file"
     */
    public function testPropertyFile()
    {

    }

    /**
     * Test attribute "line"
     */
    public function testPropertyLine()
    {

    }

    /**
     * Test attribute "function"
     */
    public function testPropertyFunction()
    {

    }

    /**
     * Test attribute "class"
     */
    public function testPropertyClass()
    {

    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "args"
     */
    public function testPropertyArgs()
    {

    }

}
